version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d/sql_scripts
      - ./production_sql_scripts:/docker-entrypoint-initdb.d/production_sql_scripts
      - ./data:/docker-entrypoint-initdb.d/data
      - ./production_data:/docker-entrypoint-initdb.d/production_data

      # SWITCH BETWEEN THE BELOW TWO INIT SCRIPTS TO SWAP FROM SAMPLE (init.sql) TO PRODUCTION (init_production.sql)
      # - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql_scripts/init_production.sql:/docker-entrypoint-initdb.d/init_production.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
